WebSRTransport/Rabbit.Shower/Models/Account.cs
using System.ComponentModel.DataAnnotations;

namespace Rabbit.Shower.Models
{
    public class Account
    {
        [Display(Name = "Login")]
        [Required(ErrorMessage = "Не заполнен логин")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Недопустимая длина логина")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Не заполнен пароль")]
        [StringLength(30, MinimumLength = 6, ErrorMessage = "Недопустимая длина пороля")]
        public string Password { get; set; }
    }

    public class AccountView: Account
    {
        public string ReturnUrl { get; set; }

        public AccountView(): base()
        {

        }

        public AccountView(string returnUrl): this()
        {
            ReturnUrl = returnUrl;
        }
    }
}

WebSRTransport/Rabbit.Shower/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rabbit.Shower.Models;
using System.Collections.Generic;
using System.Security.Claims;

namespace Rabbit.Shower.Controllers
{
    [Authorize]
    public class AccountController : AuthorizedController
    {
        public IActionResult Index()
        {
            SetAuthViewData();
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult Login(AccountView model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, model.Login)
            };
            var claimsIdentity = new ClaimsIdentity(claims, "Cookie");
            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
            HttpContext.SignInAsync("Cookie", claimsPrincipal);

            return Redirect(model.ReturnUrl ?? "/");
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync("Cookie");

            return Redirect("/");
        }
    }
}

WebSRTransport/Rabbit.Shower/Controllers/ApiController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Authontification.Controllers
{
    public class ApiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebSRTransport/Rabbit.Shower/Controllers/AuthorizedController.cs
using Microsoft.AspNetCore.Mvc;

namespace Rabbit.Shower.Controllers
{
    public class AuthorizedController : Controller
    {
        public string Login => User?.Identity.Name ?? "";
        public bool IsAuthenticated => User?.Identity.IsAuthenticated ?? false;

        public void SetAuthViewData()
        {
            ViewData[nameof(Login)] = Login;
            ViewData[nameof(IsAuthenticated)] = IsAuthenticated;
        }
    }
}

WebSRTransport/Rabbit.Shower/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Rabbit.Shower.Controllers
{
    public class HomeController : AuthorizedController
    {
        public IActionResult Index()
        {
            SetAuthViewData();
            return View();
        }
    }
}

WebSRTransport/Rabbit.Shower/Views/Home/Index.cshtml
<h1>Home/Index</h1>

<a asp-controller="Account" asp-action="Index">Account/Index</a>

WebSRTransport/Rabbit.Shower/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap-grid.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap-reboot.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap-utilities.min.css" />
</head>

@{ 
    string login = ViewData["Login"]?.ToString();
}


<body>
    <!--меню-->
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary text-dark bg-opacity-25">
        <div class="collapse navbar-collapse">
            <div class="container-xxl d-flex align-items-md-center">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item opacity-100">
                        <a asp-controller="Home"
                           asp-action="Index"
                           class="navbar-brand">Home</a>
                    </li>
                    <li class="nav-item opacity-100">
                        <a asp-controller="Account"
                           asp-action="Index" class="navbar-brand">Account</a>
                    </li>
					<li class="nav-item opacity-100">
                        <a asp-controller="Api"
                           asp-action="Index" class="navbar-brand">Api</a>
                    </li>
                </ul>
                <div class="dropdown ms-3 start-100">
                    <button class="btn btn-bd-light dropdown-toggle opacity-100" 
                            id="bd-login" 
                            data-bs-toggle="dropdown" 
                            aria-expanded="false" 
                            data-bs-display="static">
                        <span class="d-none d-lg-inline">@ViewData["Login"]</span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end"
                        aria-labelledby="bd-login">
                        @if (!string.IsNullOrWhiteSpace(login))
                        {
                            <li>
                                <a class="dropdown-item current opacity-100"
                                   aria-current="true"
                                   asp-controller="Account"
                                   asp-action="Logout">Выход </a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="dropdown-item current opacity-100"
                                   aria-current="true"
                                   asp-controller="Account"
                                   asp-action="Login">Вход </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!--основной контент-->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>© 2015 - MobileStore</p>
        </footer>
    </div>

    <script src="~/js/bootstrap.js"></script>
    @*<script src="~/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/bootstrap.esm.min.js"></script>*@
    <script src="~/js/site.js"></script>

</body>
</html>